segment_point_cloud_topic: "/depth_segmentation_node/object_segment"
world_frame_id: "world"
use_label_propagation: true

voxblox:
  voxel_size: 0.02
  voxels_per_side: 8
  truncation_distance_factor: 3.0
  voxel_carving_enabled: false
  min_ray_length_m: 0.1
  max_ray_length_m: 3.5

gsm:
  min_label_voxel_count: 20
  label_propagation_td_factor: 1.0

pairwise_confidence_merging:
  enable_pairwise_confidence_merging: true
  merging_min_overlap_ratio: 0.1
  merging_min_frame_count: 2

semantic_instance_segmentation:
  enable_semantic_instance_segmentation: false
  class_tsdk: "coco80"

publishers:
  publish_scene_map: true
  publish_scene_mesh: true
  publish_object_bbox: false

meshing:
  visualize: false
  update_mesh_every_n_sec: 0.0
  mesh_filename: "vpp_mesh.ply"
  visualizer_parameters:
    camera_position: [-0.73071,  1.35896,   6.98444,  # Position - x y z
                       0.204536, 0.470912,  0.381721, # Focal point - x y z
                      -0.945969, 0.275475, -0.171043] # View up - x y z
    clip_distances: [5.87024, 8.29843]

icp:
  enable_icp: false
  keep_track_of_icp_correction: true

debug:
  verbose_log: false
  multiple_visualizers: false
  save_visualizer_frames: false
